/* GENERATED by presenter.py — do not edit. */
window.__PRESENTER = {"s10": {"dir": "../build/av/s10", "fps": 30, "frames": 442, "lead": 0.1, "clip": "../assets/avatar-s10.mp4", "clip_secs": 14.72}, "s2": {"dir": "../build/av/s2", "fps": 30, "frames": 599, "lead": 0.11, "clip": "../assets/avatar-s2.mp4", "clip_secs": 19.96}};
