#!/usr/bin/env python3
"""
Cut the presenter clips into frame sequences for scene.html.

The two on-camera scenes (s2, s10) are HeyGen Avatar IV clips generated from the
presenter portrait and the *untrimmed* Nassim takes (../assets/avatar-s2.mp4,
../assets/avatar-s10.mp4). sync.py trims the leading silence off every take
before it lays the voice track, so a clip starts `lead` seconds before the scene's
narration does; this measures that lead the same way sync.py trims it, cuts the
clip to JPEG frames at the film's frame rate, and writes presenter.data.js so the
page can address the right frame for any t.

Frames are JPEG (q=2) rather than PNG: ~1,050 frames at 1080p is ~200 MB as JPEG
and ~1.5 GB as PNG, and the clip is itself a lossy 1080p H.264 source.
"""
import json, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.normpath(os.path.join(HERE, '..', 'assets'))
AUD = os.path.normpath(os.path.join(HERE, '..', 'audio'))
OUT = os.path.normpath(os.path.join(HERE, '..', 'build', 'av'))
FFMPEG = os.environ.get('FFMPEG') or os.path.join(HERE, 'node_modules', 'ffmpeg-static', 'ffmpeg')
FPS = int(os.environ.get('PRES_FPS', '30'))

sys.path.insert(0, HERE)
import vo as VO

CLIPS = {sid: os.path.join(ASSETS, f'avatar-{sid}.mp4') for sid in sorted(VO.PRESENTER)}
TAKE = {sid: i + 1 for i, (sid, _, _) in enumerate(VO.SCENES)}


def dur(path):
    err = subprocess.run([FFMPEG, '-hide_banner', '-i', path], capture_output=True, text=True).stderr
    for line in err.splitlines():
        if 'Duration:' in line:
            h, m, s = line.split('Duration:')[1].split(',')[0].strip().split(':')
            return int(h) * 3600 + int(m) * 60 + float(s)
    raise SystemExit(f'no duration for {path}')


def lead(take_mp3):
    """Leading silence sync.py removes from this take (same filter, start end only)."""
    tmp = os.path.join(OUT, '_lead.wav')
    subprocess.run([FFMPEG, '-hide_banner', '-loglevel', 'error', '-y', '-i', take_mp3, '-af',
                    'silenceremove=start_periods=1:start_silence=0.02:start_threshold=-50dB:detection=peak',
                    '-ar', '48000', '-ac', '1', tmp], check=True)
    d = round(dur(take_mp3) - dur(tmp), 3)
    os.remove(tmp)
    return d


def main():
    os.makedirs(OUT, exist_ok=True)
    cfg = {}
    for sid, clip in CLIPS.items():
        if not os.path.exists(clip):
            print(f'  {sid}: {os.path.relpath(clip, HERE)} missing — the still will be used')
            continue
        d = os.path.join(OUT, sid)
        take = os.path.join(AUD, f'vo-{TAKE[sid]:02d}.mp3')
        want = int(round(dur(clip) * FPS))
        have = len([f for f in os.listdir(d) if f.endswith('.jpg')]) if os.path.isdir(d) else 0
        if have != want:
            if os.path.isdir(d):
                for f in os.listdir(d): os.remove(os.path.join(d, f))
            os.makedirs(d, exist_ok=True)
            subprocess.run([FFMPEG, '-hide_banner', '-loglevel', 'error', '-y', '-i', clip,
                            '-vf', f'fps={FPS}', '-q:v', '2', os.path.join(d, '%05d.jpg')], check=True)
            # ffmpeg numbers from 00001; the page addresses from 00000
            names = sorted(f for f in os.listdir(d) if f.endswith('.jpg'))
            for i, n in enumerate(names):
                os.rename(os.path.join(d, n), os.path.join(d, f'{i:05d}.jpg'))
            have = len(names)
        cfg[sid] = {'dir': os.path.relpath(d, HERE), 'fps': FPS, 'frames': have, 'lead': lead(take),
                    'clip': os.path.relpath(clip, HERE), 'clip_secs': round(dur(clip), 2)}
        print(f'  {sid}: {have} frames @ {FPS} fps, lead {cfg[sid]["lead"]:.3f}s')
    with open(os.path.join(HERE, 'presenter.data.js'), 'w') as f:
        f.write('/* GENERATED by presenter.py — do not edit. */\n')
        f.write('window.__PRESENTER = ' + json.dumps(cfg) + ';\n')


if __name__ == '__main__':
    main()
