/* GENERATED by sync.py — do not edit. */
window.__DURATION = 275.390;
window.__SHOTS = [["s1", "Hook", 0.0, 8.8], ["s2", "Welcome", 8.8, 29.75], ["s3", "What the CMA is", 29.75, 55.0], ["s4", "Part 1", 55.0, 86.05], ["s5", "Part 2", 86.05, 115.02], ["s6", "The exam", 115.02, 152.89], ["s7", "Requirements", 152.89, 172.93], ["s8", "Why it matters", 172.93, 195.55], ["s9", "How Certuvo prepares you", 195.55, 225.16], ["s10", "AI inside", 225.16, 254.3], ["s11", "Start", 254.3, 275.39]];
