/* GENERATED by sync.py — do not edit. */
window.__DURATION = 57.570;
window.__SHOTS = [["f1", "Verified", 0.0, 10.545], ["f2", "Timed", 10.545, 17.575], ["f3", "Explained", 17.575, 24.105], ["f4", "Coach", 24.105, 30.705], ["f5", "Not alone", 30.705, 37.295], ["f6", "The gap", 37.295, 42.545], ["f7", "Ready", 42.545, 57.57]];
