/* GENERATED by sync.py — do not edit. */
window.__DURATION = 137.960;
window.__SHOTS = [["s1", "The question", 0.0, 10.97], ["s2", "The recognition", 10.97, 24.41], ["s3", "What it is", 24.41, 36.95], ["s4", "Who may apply", 36.95, 50.25], ["s5", "Global industries", 50.25, 61.91], ["s6", "Experience", 61.91, 77.68], ["s7", "Your application", 77.68, 90.59], ["s8", "Recognition", 90.59, 116.04], ["s9", "Discipline alignment", 116.04, 124.18], ["s10", "Apply", 124.18, 137.96]];
