/* GENERATED by sync.py — do not edit. */
window.__DURATION = 119.500;
window.__SHOTS = [["s1", "The question", 0.0, 8.409], ["s2", "The recognition", 8.409, 18.53], ["s3", "What it is", 18.53, 31.893], ["s4", "Who may apply", 31.893, 41.639], ["s5", "Global industries", 41.639, 53.328], ["s6", "Experience", 53.328, 68.356], ["s7", "Your evidence", 68.356, 82.45], ["s8", "Recognition", 82.45, 100.249], ["s9", "Discipline alignment", 100.249, 107.147], ["s10", "Apply", 107.147, 119.5]];
