/* GENERATED by sync.py — do not edit. */
window.__DURATION = 120.000;
window.__SHOTS = [["s1", "The question", 0.0, 8.075], ["s2", "The recognition", 8.075, 17.772], ["s3", "What it is", 17.772, 30.593], ["s4", "Who may apply", 30.593, 39.929], ["s5", "Global industries", 39.929, 51.137], ["s6", "Experience", 51.137, 65.562], ["s7", "Your evidence", 65.562, 79.088], ["s8", "Recognition", 79.088, 101.626], ["s9", "Discipline alignment", 101.626, 108.217], ["s10", "Apply", 108.217, 120.0]];
