/* GENERATED by presenter.py — do not edit. */
window.__PRESENTER = {"s1": {"dir": "../build/av/s1", "fps": 30, "frames": 442, "lead": 0.12, "clip": "../assets/avatar-s1.mp4", "clip_secs": 14.72}, "s11": {"dir": "../build/av/s11", "fps": 30, "frames": 242, "lead": 0.04, "clip": "../assets/avatar-s11.mp4", "clip_secs": 8.09}};
