/* GENERATED by sync.py — do not edit. */
window.__DURATION = 165.760;
window.__SHOTS = [["s1", "Late", 0.0, 15.215], ["s2", "The difference", 15.215, 26.565], ["s3", "Ten credentials", 26.565, 47.995], ["s4", "Official partner", 47.995, 55.195], ["s5", "Already inside", 55.195, 72.305], ["s6", "Four judges", 72.305, 90.815], ["s7", "AI Coach", 90.815, 107.545], ["s8", "Study with a peer", 107.545, 123.915], ["s9", "Readiness", 123.915, 137.135], ["s10", "Start free", 137.135, 145.105], ["s11", "What you work with", 145.105, 165.76]];
