/* GENERATED by sync.py — do not edit. */
window.__DURATION = 162.110;
window.__SHOTS = [["s1", "Late", 0.0, 15.215], ["s2", "The difference", 15.215, 25.735], ["s3", "Ten credentials", 25.735, 49.085], ["s4", "Official partner", 49.085, 56.405], ["s5", "Already inside", 56.405, 73.455], ["s6", "Four judges", 73.455, 91.305], ["s7", "AI Coach", 91.305, 109.595], ["s8", "Not alone", 109.595, 120.995], ["s9", "Readiness", 120.995, 133.575], ["s10", "Start free", 133.575, 141.455], ["s11", "What you work with", 141.455, 162.11]];
