/* GENERATED by sync.py — do not edit. */
window.__DURATION = 137.180;
window.__SHOTS = [["s1", "Late", 0.0, 15.215], ["s2", "What it is worth", 15.215, 26.655], ["s3", "Ten credentials", 26.655, 48.895], ["s4", "Official partner", 48.895, 56.405], ["s5", "Built on research", 56.405, 68.135], ["s6", "What is inside", 68.135, 79.005], ["s7", "AI inside", 79.005, 95.215], ["s8", "Not alone", 95.215, 109.505], ["s9", "The price", 109.505, 118.055], ["s10", "Start free", 118.055, 123.325], ["s11", "One platform", 123.325, 137.18]];
