/* GENERATED by sync.py — do not edit. */
window.__DURATION = 65.760;
window.__SHOTS = [["f1", "Sit down", 0.0, 8.795], ["f2", "Twenty minutes", 8.795, 16.345], ["f3", "You get one wrong", 16.345, 25.055], ["f4", "You call", 25.055, 33.995], ["f5", "You are not alone", 33.995, 43.295], ["f6", "What it noticed", 43.295, 53.345], ["f7", "Close the laptop", 53.345, 65.76]];
