/* GENERATED by presenter.py — do not edit. */
window.__PRESENTER = {"s1": {"dir": "../build/av/s1", "fps": 30, "frames": 115, "lead": 0.1, "clip": "../assets/avatar-s1.mp4", "clip_secs": 3.84}, "s4": {"dir": "../build/av/s4", "fps": 30, "frames": 149, "lead": 0.22, "clip": "../assets/avatar-s4.mp4", "clip_secs": 4.97}};
