/* GENERATED by sync.py — do not edit. */
window.__DURATION = 50.950;
window.__SHOTS = [["s1", "Hook", 0.0, 4.62], ["s2", "What you get", 4.62, 22.87], ["s3", "AI inside", 22.87, 41.13], ["s4", "Start", 41.13, 50.95]];
