/* GENERATED by sync.py — do not edit. */
window.__DURATION = 64.730;
window.__SHOTS = [["f1", "The bank", 0.0, 11.885], ["f2", "Under timing", 11.885, 19.055], ["f3", "Why, not just what", 19.055, 29.405], ["f4", "The Coach", 29.405, 38.735], ["f5", "Together, and in one place", 38.735, 46.175], ["f6", "What it finds", 46.175, 52.865], ["f7", "Where you are", 52.865, 64.73]];
